DROP TABLE IF EXISTS nhlstats.game_details;

CREATE TABLE nhlstats.game_details (
    gamepk              INTEGER,
    game_season         INTEGER,
    game_type           VARCHAR,
    date_time           TIMESTAMP,
    end_date_time       TIMESTAMP,
    abstract_game_state VARCHAR,
    coded_game_state    VARCHAR,
    detailed_state      VARCHAR,
    status_code         INTEGER,
    start_time_tbd      VARCHAR,
    away_id             INTEGER,
    away_franchise_id   INTEGER,
    home_id             INTEGER,
    home_franchise_id   INTEGER,
    venue_id            INTEGER,
    venue_name          VARCHAR,
    venue_link          VARCHAR,
    home_goals          REAL,
    home_pim            REAL,
    home_shots          REAL,
    home_ppperc         REAL,
    home_ppgoals        REAL,
    home_ppopp          REAL,
    home_fowperc        REAL,
    home_blocked        REAL,
    home_takeaways      REAL,
    home_giveaways      REAL,
    home_hits           REAL,
    away_goals          REAL,
    away_pim            REAL,
    away_shots          REAL,
    away_ppperc         REAL,
    away_ppgoals        REAL,
    away_ppopp          REAL,
    away_fowperc        REAL,
    away_blocked        REAL,
    away_takeaways      REAL,
    away_giveaways      REAL,
    away_hits           REAL,
    created             TIMESTAMP DEFAULT current_timestamp,
    PRIMARY KEY(gamepk)
);