DROP TABLE IF EXISTS nhlstats.yearly_averages;

CREATE TABLE nhlstats.yearly_averages (
    year_code                      INT        NOT NULL,
    month                          VARCHAR        NOT NULL,
    game_type                      VARCHAR        NOT NULL,
    num_shots                      REAL,
    num_goals                      REAL,
    sum_xgoals                     REAL,
    avg_shoot_perc                 REAL,

    avg_xgoals                     REAL,
    avg_xgoals_wrist_shot          REAL,
    avg_xgoals_backhand            REAL,
    avg_xgoals_slap_shot           REAL,
    avg_xgoals_snap_shot           REAL,
    avg_xgoals_tip_in              REAL,
    avg_xgoals_deflected           REAL,
    avg_xgoals_wrap_around         REAL,

    goals_aa_per_shot              REAL,

    wrist_shot_num                 REAL,
    backhand_num                   REAL,
    slap_shot_num                  REAL,
    snap_shot_num                  REAL,
    tip_in_num                     REAL,
    deflected_num                  REAL,
    wrap_around_num                REAL,

    wrist_shot_pred                 REAL,
    backhand_pred                   REAL,
    slap_shot_pred                  REAL,
    snap_shot_pred                  REAL,
    tip_in_pred                     REAL,
    deflected_pred                  REAL,
    wrap_around_pred                REAL,

    wrist_shot_freq                REAL,
    backhand_freq                  REAL,
    slap_shot_freq                 REAL,
    snap_shot_freq                 REAL,
    tip_in_freq                    REAL,
    deflected_freq                 REAL,
    wrap_around_freq               REAL,
    wrist_shot_shooting_perc       REAL,
    backhand_shooting_perc         REAL,
    slap_shot_shooting_perc        REAL,
    snap_shot_shooting_perc        REAL,
    tip_in_shooting_perc           REAL,
    deflected_shooting_perc        REAL,
    wrap_around_shooting_perc      REAL,
    mean_dist                      REAL,
    mean_ang                       REAL,
    created                        TIMESTAMP DEFAULT current_timestamp,
    PRIMARY KEY(year_code, month, game_type)
);
